'use strict';

// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT = 'LOGOUT';

// user
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const DELETE_USER = 'DELETE_USER';

// leagues
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAILURE = 'CREATE_LEAGUE_FAILURE';

// characters
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE';

// UI
export const CHANGE_MAIN_COMPONENT = 'CHANGE_MAIN_COMPONENT';
export const CHANGE_AUTH_DISPLAY = 'CHANGE_AUTH_DISPLAY';

// drafting
export const DRAFT_CHARACTER_SUCCESS = 'DRAFT_CHARACTER_SUCCESS';
export const DRAFT_CHARACTER_FAILURE = 'DRAFT_CHARACTER_FAILURE';